/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        'primary-hover': '#0a3d8f',
        'primary-container': '#3366cc',
        'primary-fixed': '#d9e2ff',
        'primary-fixed-dim': '#b1c5ff',
        tertiary: '#6d5e00',
        'tertiary-container': '#bfab49',
        'tertiary-fixed': '#f9e37a',
        'tertiary-fixed-dim': '#dcc661',
        secondary: 'var(--text-secondary)',
        'secondary-container': '#dfe3e8',
        surface: 'var(--bg)',
        'surface-dim': '#dbdadb',
        'surface-bright': 'var(--bg)',
        'surface-variant': '#e3e2e3',
        'surface-lowest': 'var(--card)',
        'surface-low': 'color-mix(in srgb, var(--card) 95%, var(--border))',
        'surface-mid': 'color-mix(in srgb, var(--card) 90%, var(--border))',
        'surface-high': 'color-mix(in srgb, var(--card) 85%, var(--border))',
        'surface-highest': 'color-mix(in srgb, var(--card) 80%, var(--border))',
        'on-surface': 'var(--text-primary)',
        'on-variant': 'var(--text-secondary)',
        'on-primary': '#ffffff',
        outline: '#737784',
        'outline-variant': 'var(--border)',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['"Public Sans"', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        card: '0 1px 3px rgba(27,28,29,0.06), 0 1px 2px rgba(27,28,29,0.04)',
        modal: '0 24px 48px rgba(27,28,29,0.06), 0 8px 16px rgba(27,28,29,0.04)',
        fab: '0 6px 20px rgba(9,76,178,0.25)',
      },
    },
  },
  plugins: [],
};
