/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#094cb2',
        'primary-hover': '#0a3d8f',
        'primary-container': '#3366cc',
        'primary-fixed': '#d9e2ff',
        'primary-fixed-dim': '#b1c5ff',
        tertiary: '#6d5e00',
        'tertiary-container': '#bfab49',
        'tertiary-fixed': '#f9e37a',
        'tertiary-fixed-dim': '#dcc661',
        secondary: '#5a5f63',
        'secondary-container': '#dfe3e8',
        surface: '#faf9fa',
        'surface-dim': '#dbdadb',
        'surface-bright': '#faf9fa',
        'surface-variant': '#e3e2e3',
        'surface-lowest': '#ffffff',
        'surface-low': '#f5f3f4',
        'surface-mid': '#efedee',
        'surface-high': '#e9e8e9',
        'surface-highest': '#e3e2e3',
        'on-surface': '#1b1c1d',
        'on-variant': '#434653',
        'on-primary': '#ffffff',
        outline: '#737784',
        'outline-variant': '#c3c6d5',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['"Public Sans"', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        card: '0 1px 3px rgba(27,28,29,0.06), 0 1px 2px rgba(27,28,29,0.04)',
        modal: '0 24px 48px rgba(27,28,29,0.06), 0 8px 16px rgba(27,28,29,0.04)',
        fab: '0 6px 20px rgba(9,76,178,0.25)',
      },
    },
  },
  plugins: [],
};
